DEVDOCS-5997: International Enhancements for MSF, update `properties` field for channel locale only
bigcommerce/docs pull request #352
Opened 2024-06-25 17:27 UTC by bc-andreadao

# [DEVDOCS-5997]

## What changed?
* Mention that `properties` field is for channel locale only
* Link back to MSF International Enhancements overview (so developers know currently, the only way to update the overrides is through the GQL Admin API)

## Release notes draft

n / a

* 

## Anything else?

ping {names}

2024-06-26 10:01 UTC, kristinapototska requested changes

2024-06-26 10:01 UTC, kristinapototska commented on docs/integrations/webhooks/events/index.mdx
> +| store/modifier/updated | Fires when you edit attributes for a local or shared modifier. Updates to the global store and channel locale as an override triggers the webhook.<br /><br />The `propertie
`Context` is available for options, modifiers and product and is present for only updates to overrides. So we need to keep this part of the message for all 3 webhooks.
`Properties` should only be added to `store/product/updated` webhook message.

2024-06-26 14:52 UTC, bc-andreadao commented on docs/integrations/webhooks/events/index.mdx
> +| store/modifier/updated | Fires when you edit attributes for a local or shared modifier. Updates to the global store and channel locale as an override triggers the webhook.<br /><br />The `propertie
Thanks @kristinapototska , I fixed the PR. Let me know if there's anything else

2024-07-01 15:33 UTC, bc-traciporter approved these changes
Approved

2024-07-01 15:44 UTC, merged