DEVDOCS-6034 [update]: Settings API, update docs for channel overrides
bigcommerce/docs pull request #448
Opened 2024-08-13 21:15 UTC by bc-andreadao

# [DEVDOCS-6034]

This PR addresses [issue 388](https://github.com/bigcommerce/docs/issues/388)

## What changed?

* add `channel_id` query parameter
* Update the request for [Update Locale Settings](https://developer.bigcommerce.com/docs/rest-management/settings/store-locale#update-locale-settings) to take into account how to remove overrides 
* Update response schema (If there are no channel overrides, `data` will be `null` )

## Release notes draft
N / A

## Anything else?
@bigcommerce/team-multi-storefront

2024-08-14 19:07 UTC, funivan requested changes
We need to talk with product first. 

Blocking this PR because of this change: `- $ref: '#/components/parameters/ChannelIdParam'`

2024-08-14 20:26 UTC, bc-andreadao commented
Thanks @funivan, keep me in the loop on the conversation

2024-08-16 08:32 UTC, kristinapototska commented
@bc-andreadao is there someone requesting this change to documentation?
I'm asking, because we have intentionally removed this from documentation as we are not planning to make this change public and instead we will be release a separate API endpoint to manage locales per channel.

2024-08-16 15:32 UTC, bc-andreadao commented
@kristinapototska I was created to address https://github.com/bigcommerce/docs/issues/388 from an external developer. However, I can close out the PR and notify them that we're planning to release a separate API endpoint in the future, if that's what you'd prefer.

2024-12-11 16:40 UTC, closed without merging