DEVDOCS-5858:[new] add headless channel doc
bigcommerce/docs pull request #715
Opened 2024-12-17 20:05 UTC by bc-traciporter

# [DEVDOCS-5858]

## What changed?
Add new B2B storefront headless doc

## Release notes draft

* 

## Anything else?

ping {names}

2024-12-17 21:43 UTC, bc-traciporter commented
Preview
![2024-12-17_15-39-49](https://github.com/user-attachments/assets/af5ad002-3501-46bd-8349-29eb670b5789)

2024-12-19 18:28 UTC, bc-micah requested changes

2024-12-19 18:28 UTC, bc-micah commented on docs/b2b-edition/headless.mdx
> +}'
```suggestion
{
    "name": "<the name you want for your channel>",
    "platform": "<desired platform>",
    "type": "storefront",
    "status": "active",
    "is_listable_from_ui": true,
    "is_visible": true
}
```

2024-12-19 18:28 UTC, bc-micah commented on docs/b2b-edition/headless.mdx
> +}'
```suggestion
{
  "channel_id": <channel returned on the first request>,
  "expires_at": <Unix timestamp (UTC time) defining when the token should expire. Supports seconds, but does not support milliseconds, microseconds, or nanoseconds.>
}
```

2024-12-19 18:28 UTC, bc-micah commented on docs/b2b-edition/headless.mdx
> +}'
```suggestion
{
    "url": <url you want to point>,
    "channel_id": <the channel id returned on step 1>
}
```

2024-12-19 18:28 UTC, bc-micah commented on docs/b2b-edition/headless.mdx
> +```
```suggestion
```html copy
<script
  type="module"
  data-storehash="{STORE_HASH}"
  data-channelid="{CHANNEL_ID}"
  src="https://cdn.bundleb2b.net/b2b/production/storefront/headless.js"
></script>
```
```

2024-12-19 18:28 UTC, bc-micah commented on docs/b2b-edition/headless.mdx
> + </Callout>
This does not need to be shared with merchants.

2024-12-20 21:43 UTC, bc-traciporter commented
Hi @bc-micah can you approve?

Can I post this new article after approval?

2025-01-06 17:19 UTC, bc-micah approved these changes
thanks for fixing those - looks good

2025-01-06 17:26 UTC, merged